services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      MONGODB_URI: mongodb://DB_USER:DB_PASSWORD@database:27017/?authSource=admin
    depends_on:
      - database

  database:
    image: mongo:4.4
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    volumes:
      - ./local/database/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: DB_USER
      MONGO_INITDB_ROOT_PASSWORD: DB_PASSWORD
